public class X12 {
    public static void main(String[] args) {
        boolean re = true;
        for (int x = 1; re; x++) {
            int q = (x * (x + 1)) / 2;
            int d = 1;

            for (int z = 1; z <= q / 2; z++) {
                if (q % z == 0) {
                    d++;
                }
            }
            if (d >= 500) {
                re = false;
            }
        }
    }
}
/*
 * The sequence of triangle numbers is generated by adding the natural numbers.
 * So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first
 * ten terms would be:
 * 
 * 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
 * 
 * Let us list the factors of the first seven triangle numbers:
 * 
 * 1: 1 3: 1,3 6: 1,2,3,6 10: 1,2,5,10 15: 1,3,5,15 21: 1,3,7,21 28:
 * 1,2,4,7,14,28 We can see that 28 is the first triangle number to have over
 * five divisors.
 * 
 * What is the value of the first triangle number to have over five hundred
 * divisors?
 */