public class x2 {
	public static void main(String[] args) {
		int c = 0;
		int n0 = 0;
		int n1 = 2;
		int n2 = 1;

		while (n0 < 4000000) {
			n0 = n1 + n2;

			if (n0 % 2 == 0) {
				c += n0;
			}

			n2 = n1;
			n1 = n0;
		}
		System.out.println(c + 2);
	}
}
/*
 * Each new term in the Fibonacci sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed
 * four million, find the sum of the even-valued terms.
 */